=== DanielLEVY25021961/traficweb_v1/src/test/resources/differentstypesfichiers/texte/bouteilles_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2016 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ph">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="7,45"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ville">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="St-Cyr la Source"/>
				<xs:enumeration value="Vichy"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="marque">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Cristaline"/>
				<xs:enumeration value="Vichy Saint-Yorre"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="source">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ville"/>
				<xs:element ref="departement"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="bouteille">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="marque"/>
				<xs:element ref="composition"/>
				<xs:element ref="source"/>
				<xs:element ref="code_barre"/>
				<xs:element ref="contenance"/>
				<xs:element ref="ph"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="bouteilles">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="bouteille" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="code_barre">
		<xs:simpleType>
			<xs:restriction base="xs:long">
				<xs:enumeration value="3274080005003"/>
				<xs:enumeration value="3274080005007"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="contenance">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="125cl"/>
				<xs:enumeration value="150cl"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="composition">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ion_positif" maxOccurs="unbounded"/>
				<xs:element ref="ion_negatif"/>
				<xs:element ref="ion_positif"/>
				<xs:element ref="ion_negatif"/>
				<xs:element ref="autres_materiaux"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="departement">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Allier"/>
				<xs:enumeration value="Loiret"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ion_negatif">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="chlorure 20mg/l"/>
				<xs:enumeration value="nitrate 1mg/l"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ion_positif">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="calcium 71mg/l"/>
				<xs:enumeration value="calcium 91mg/l"/>
				<xs:enumeration value="magnÃ©sium 5,5mg/l"/>
				<xs:enumeration value="sodium 110mg/l"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="autres_materiaux">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="fer"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== DanielLEVY25021961/traficweb_v1/src/test/resources/differentstypesfichiers/texte/bouteilles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- APPEL DE LA FEUILLE DE STYLE POUR LA TRANSFORMATION XSLT avec un chemin RELATIF par rapport au présent document XML -->
<!-- Instruction de traitement -->
<?xml-stylesheet type="text/xsl" href="..\Transformations_xslt_exemples\bouteilles_transformation.xslt"?>
<!-- SCHEMA (Grammaire) -->
<!-- xsi:noNamespaceSchemaLocation="../schemas_xml_exemples/bouteilles_schema.xsd" permet d'indiquer le chemin RELATIF du schéma par rapport au présent document XML -->
<bouteilles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas_xml_exemples/bouteilles_schema.xsd">
	<bouteille>
		<marque>Cristaline</marque>
		<composition>
			<ion_positif>calcium 71mg/l</ion_positif>
			<ion_negatif>nitrate 1mg/l</ion_negatif>
			<ion_positif>magnésium 5,5mg/l</ion_positif>
			<ion_negatif>chlorure 20mg/l</ion_negatif>
			<autres_materiaux>fer</autres_materiaux>
		</composition>
		<source>
			<ville>St-Cyr la Source</ville>
			<departement>Loiret</departement>
		</source>
		<code_barre>3274080005003</code_barre>
		<contenance>150cl</contenance>
		<ph>7,45</ph>
	</bouteille>
	<bouteille>
		<marque>Vichy Saint-Yorre</marque>
		<composition>
			<ion_positif>calcium 91mg/l</ion_positif>
			<ion_positif>sodium 110mg/l</ion_positif>
			<ion_negatif>nitrate 1mg/l</ion_negatif>
			<ion_positif>magnésium 5,5mg/l</ion_positif>
			<ion_negatif>chlorure 20mg/l</ion_negatif>
			<autres_materiaux>fer</autres_materiaux>
		</composition>
		<source>
			<ville>Vichy</ville>
			<departement>Allier</departement>
		</source>
		<code_barre>3274080005007</code_barre>
		<contenance>125cl</contenance>
		<ph>7,45</ph>
	</bouteille>
</bouteilles>
